sudo: required
services:
  - docker

before_install:
  - docker build -t yogihulk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yogihulk/react-test npm test

after_success:
  - docker build -t yogihulk/multi-client ./client
  - docker build -t yogihulk/multi-nginx ./nginx
  - docker build -t yogihulk/multi-server ./server
  - docker build -t yogihulk/multi-worker ./worker
