sudo: required
services:
  - docker

before_install:
  - docker build -t yogihulk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yogihulk/react-test npm test

after_success:
  - docker build -t yogihulk/multi-client ./client
  - docker build -t yogihulk/multi-nginx ./nginx
  - docker build -t yogihulk/multi-server ./server
  - docker build -t yogihulk/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push yogihulk/multi-client
  - docker push yogihulk/multi-nginx
  - docker push yogihulk/multi-server
  - docker push yogihulk/multi-worker